"""Add short_name column to teams table

Revision ID: 0a1e4e4dba34
Revises: a7b16a38b68c
Create Date: 2026-03-12 03:28:37.017480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1e4e4dba34'
down_revision: Union[str, Sequence[str], None] = 'a7b16a38b68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('teams', sa.Column('short_name', sa.String(), nullable=True))

    # Populate short_name for all teams
    short_names = {
        "AEK": "AEK Athens",
        "ARI": "Aris",
        "ASV": "ASVEL",
        "AVE": "Avellino",
        "BAM": "Brose Bamberg",
        "BAR": "Barcelona",
        "BAS": "Baskonia",
        "BER": "Alba Berlin",
        "BES": "Besiktas",
        "BIL": "Bilbao Basket",
        "BUD": "Buducnost",
        "CAN": "Gran Canaria",
        "CED": "Cedevita",
        "CHA": "Spirou Charleroi",
        "CHL": "Chalon",
        "CHO": "Cholet",
        "CIB": "Cibona",
        "COL": "Cologne",
        "CSK": "CSKA Moscow",
        "CTU": "Cantu",
        "DAR": "Darussafaka",
        "DUB": "Dubai",
        "DYN": "Dynamo Moscow",
        "DYR": "Zenit SPB",
        "EST": "Estudiantes",
        "FOR": "Fortitudo Bologna",
        "FRA": "Skyliners Frankfurt",
        "GAL": "Galatasaray",
        "GSS": "Zielona Gora",
        "HTA": "Hapoel Tel Aviv",
        "IST": "Anadolu Efes",
        "JER": "Hapoel Jerusalem",
        "JOV": "Joventut",
        "KHI": "Khimki",
        "KLA": "Neptunas",
        "KSK": "Karsiyaka",
        "LEM": "Le Mans",
        "LIE": "Lietuvos Rytas",
        "LJU": "Olimpija",
        "LMG": "Limoges",
        "LON": "London Towers",
        "LUG": "Lugano",
        "MAD": "Real Madrid",
        "MAL": "Unicaja",
        "MAR": "Maroussi",
        "MCO": "Monaco",
        "MES": "Krka",
        "MIL": "Armani Milano",
        "MUN": "Bayern Munich",
        "NAN": "Nancy",
        "NAP": "Napoli",
        "NIK": "Budivelnik",
        "NIO": "Panionios",
        "NOV": "Nizhny Novgorod",
        "NTR": "Nanterre",
        "OLD": "EWE Baskets",
        "OLY": "Olympiacos",
        "OOS": "Oostende",
        "ORL": "Orleans",
        "OVA": "Ovarense",
        "PAM": "Valencia",
        "PAN": "Panathinaikos",
        "PAO": "PAOK",
        "PAR": "Partizan",
        "PAU": "Pau-Orthez",
        "PEM": "Ural Great",
        "PER": "Peristeri",
        "PES": "Pesaro",
        "PET": "SPB Lions",
        "PRS": "Paris Basketball",
        "RED": "Crvena Zvezda",
        "ROA": "Roanne",
        "ROM": "Roma",
        "SAS": "Sassari",
        "SIE": "Siena",
        "SOP": "Prokom Gdynia",
        "STR": "Strasbourg",
        "TEL": "Maccabi Tel Aviv",
        "TIV": "Lokomotiv Kuban",
        "TRE": "Benetton",
        "ULK": "Fenerbahce",
        "UNK": "UNICS Kazan",
        "VER": "Verona",
        "VIR": "Virtus Bologna",
        "WRO": "Slask Wroclaw",
        "ZAD": "Zadar",
        "ZAG": "Zagreb",
        "ZAL": "Zalgiris",
        "ZGO": "Turow",
    }
    conn = op.get_bind()
    for code, short in short_names.items():
        conn.execute(
            sa.text("UPDATE teams SET short_name = :short WHERE euroleague_code = :code"),
            {"short": short, "code": code},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'short_name')
    # ### end Alembic commands ###
