"""initial schema

Revision ID: 321668000356
Revises: 
Create Date: 2026-02-24 04:16:18.910471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321668000356'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('euroleague_code', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_euroleague_code'), 'players', ['euroleague_code'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('euroleague_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_euroleague_code'), 'teams', ['euroleague_code'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('champion_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('euroleague_gamecode', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('game_date', sa.String(), nullable=True),
    sa.Column('game_time', sa.String(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'euroleague_gamecode', name='uq_season_gamecode')
    )
    op.create_table('player_season_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.String(), nullable=True),
    sa.Column('registration_start', sa.Date(), nullable=True),
    sa.Column('registration_end', sa.Date(), nullable=True),
    sa.Column('first_game_round', sa.Integer(), nullable=True),
    sa.Column('last_game_round', sa.Integer(), nullable=True),
    sa.Column('is_champion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_id', 'season_id', name='uq_player_team_season')
    )
    op.create_table('team_seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_name_that_season', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season_id', name='uq_team_season')
    )
    op.create_table('game_player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=True),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('two_points_made', sa.Integer(), nullable=True),
    sa.Column('two_points_attempted', sa.Integer(), nullable=True),
    sa.Column('three_points_made', sa.Integer(), nullable=True),
    sa.Column('three_points_attempted', sa.Integer(), nullable=True),
    sa.Column('free_throws_made', sa.Integer(), nullable=True),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=True),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('total_rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks_favor', sa.Integer(), nullable=True),
    sa.Column('blocks_against', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('fouls_received', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('pir', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'team_id', name='uq_game_player_team')
    )
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_season_team_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('two_points_made', sa.Integer(), nullable=True),
    sa.Column('two_points_attempted', sa.Integer(), nullable=True),
    sa.Column('three_points_made', sa.Integer(), nullable=True),
    sa.Column('three_points_attempted', sa.Integer(), nullable=True),
    sa.Column('free_throws_made', sa.Integer(), nullable=True),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=True),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('total_rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks_favor', sa.Integer(), nullable=True),
    sa.Column('blocks_against', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('fouls_received', sa.Integer(), nullable=True),
    sa.Column('pir', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_season_team_id'], ['player_season_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_season_team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_season_stats')
    op.drop_table('game_player_stats')
    op.drop_table('team_seasons')
    op.drop_table('player_season_teams')
    op.drop_table('games')
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_teams_euroleague_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_euroleague_code'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
