"""add quiz_ttt_axes table

Revision ID: 3343ba02291a
Revises: 4b7e2c1d9f03
Create Date: 2026-02-24 12:47:50.943553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3343ba02291a'
down_revision: Union[str, Sequence[str], None] = '4b7e2c1d9f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_ttt_axes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('axis_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('display_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['quiz_ttt_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'position', name='uq_quiz_ttt_axis')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_ttt_axes')
    # ### end Alembic commands ###
