"""add_higher_lower_tables

Revision ID: 37371260409a
Revises: cfc9cec51414
Create Date: 2026-02-27 23:19:52.263070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37371260409a'
down_revision: Union[str, Sequence[str], None] = 'cfc9cec51414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('higher_lower_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('season_range_start', sa.Integer(), nullable=False),
    sa.Column('season_range_end', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('left_player_id', sa.Integer(), nullable=True),
    sa.Column('right_player_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('left_value', sa.Integer(), nullable=True),
    sa.Column('right_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('higher_lower_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_higher_lower_scores_nickname'), 'higher_lower_scores', ['nickname'], unique=False)
    op.create_index(op.f('ix_higher_lower_scores_tier'), 'higher_lower_scores', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_higher_lower_scores_tier'), table_name='higher_lower_scores')
    op.drop_index(op.f('ix_higher_lower_scores_nickname'), table_name='higher_lower_scores')
    op.drop_table('higher_lower_scores')
    op.drop_table('higher_lower_games')
    # ### end Alembic commands ###
