"""Add image_url column to players table

Revision ID: 831b7794e96f
Revises: 0a1e4e4dba34
Create Date: 2026-03-12 04:17:07.638981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831b7794e96f'
down_revision: Union[str, Sequence[str], None] = '0a1e4e4dba34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'image_url')
    # ### end Alembic commands ###
