"""add roster guess game models

Revision ID: cfc9cec51414
Revises: 7f103151b2ef
Create Date: 2026-02-27 09:10:08.628531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc9cec51414'
down_revision: Union[str, Sequence[str], None] = '7f103151b2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_guess_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(length=6), nullable=True),
    sa.Column('target_wins', sa.Integer(), nullable=False),
    sa.Column('turn_seconds', sa.Integer(), nullable=True),
    sa.Column('turn_started_at', sa.DateTime(), nullable=True),
    sa.Column('player1_name', sa.String(), nullable=True),
    sa.Column('player2_name', sa.String(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=False),
    sa.Column('player2_score', sa.Integer(), nullable=False),
    sa.Column('current_player', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('winner_player', sa.Integer(), nullable=True),
    sa.Column('season_range_start', sa.Integer(), nullable=False),
    sa.Column('season_range_end', sa.Integer(), nullable=False),
    sa.Column('pending_end_from', sa.Integer(), nullable=True),
    sa.Column('pending_end_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_guess_games_join_code'), 'roster_guess_games', ['join_code'], unique=True)
    op.create_table('roster_guess_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('player1_correct', sa.Integer(), nullable=False),
    sa.Column('player2_correct', sa.Integer(), nullable=False),
    sa.Column('winner_player', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['roster_guess_games.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'round_number', name='uq_roster_guess_round')
    )
    op.create_table('roster_guess_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('player_season_team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('guessed_by_player', sa.Integer(), nullable=True),
    sa.Column('guessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_season_team_id'], ['player_season_teams.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['roster_guess_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'player_id', name='uq_roster_guess_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_guess_slots')
    op.drop_table('roster_guess_rounds')
    op.drop_index(op.f('ix_roster_guess_games_join_code'), table_name='roster_guess_games')
    op.drop_table('roster_guess_games')
    # ### end Alembic commands ###
